name: Storybook deploy and publish package
on:
  push:
    branches:
      # - master
      - feature/CI-CD

jobs:
  deploy-storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install Dependencies
        run: yarn

      - name: Build storybook
        run: yarn build-storybook

      - name: Deploy storybook
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            build s3://design.luckypear.io

  publish-npm:
    needs: deploy-storybook
    runs-on: ubuntu-latest
    steps:
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install Dependencies
        run: yarn
        
      - name: Build package
        run: yarn build

      - name: Build package types
        run: yarn build:types
      
      - name: Test dist configuration
        run: cat dist/index.js

      # - name: Semantic release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      #   run: npx semantic-release

